[api-diff] Compute the API diff using the public (stable) NuGet instead of downloading custom zip files.

diff --git a/tools/apidiff/Makefile b/tools/apidiff/Makefile
--- a/tools/apidiff/Makefile
+++ b/tools/apidiff/Makefile
@@ -30,13 +30,6 @@ export HTML_NO_BREAKING_CHANGES_MESSAGE=No breaking changes
 export MARKDOWN_BREAKING_CHANGES_MESSAGE=:heavy_exclamation_mark: Breaking changes :heavy_exclamation_mark:
 export MARKDOWN_NO_BREAKING_CHANGES_MESSAGE=No breaking changes
 
-ifeq ($(DOTNET_TFM_REFERENCE),)
-# Change the below to net9.0 once we have reference assemblies from net9.0 (i.e. once net8.0 goes stable).
-DOTNET_TFM_REFERENCE=net8.0
-endif
-
-DOTNET_ASSEMBLIES = $(foreach platform,$(DOTNET_PLATFORMS),Microsoft.$(platform).Ref/ref/$(DOTNET_TFM)/Microsoft.$(platform))
-
 APIDIFF_IGNORE = -i 'INSObjectProtocol'
 
 $(MONO_API_INFO): $(wildcard $(API_TOOLS_PATH)/mono-api-info/*.cs*)
@@ -47,14 +40,6 @@ $(MONO_API_HTML): $(wildcard $(API_TOOLS_PATH)/mono-api-html/*.cs*)
 	$(Q) $(DOTNET) build $(API_TOOLS_PATH)/mono-api-html/mono-api-html.csproj /bl:$@.binlog $(MSBUILD_VERBOSITY)
 	$(Q) touch $@
 
-# create api info.
-define DotNetApiInfo
-$(APIDIFF_DIR)/temp/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).xml: $(DOTNET_DESTDIR)/$($(1)_NUGET_REF_NAME)/ref/$(DOTNET_TFM)/Microsoft.$(1).dll $(MONO_API_INFO)
-	$$(Q) mkdir -p $$(dir $$@)
-	$$(QF_GEN) $(MONO_API_INFO_EXEC) $$(abspath $$<) -o $$(abspath $$@)
-endef
-$(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call DotNetApiInfo,$(platform))))
-
 # create diff from api info and reference info
 # note that we create an empty file (the 'touch' command)
 # so that we get a file in all cases (so that we don't have 
@@ -62,10 +47,13 @@ $(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call DotNetApiInfo,$(platform)))
 # dependencies changed)
 
 define DotNetComputeDiff
-$(OUTPUT_DIR)/diff/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1)%html $(OUTPUT_DIR)/diff/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1)%md: $(APIDIFF_DIR)/temp/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1)%xml $(APIDIFF_DIR)/references/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM_REFERENCE)/Microsoft.$(1).xml $(MONO_API_HTML)
+$(OUTPUT_DIR)/diff/Microsoft.$(1)%html $(OUTPUT_DIR)/diff/Microsoft.$(1)%md: $(APIDIFF_DIR)/references/current/Microsoft.$(1)%xml $(APIDIFF_DIR)/references/comparison/Microsoft.$(1).xml $(MONO_API_HTML)
 	$$(Q) mkdir -p $$(dir $$@)
-	$$(QF_GEN) $(MONO_API_HTML_EXEC) $(NEW_REGEX) $(ADD_REGEX) $$(abspath $(APIDIFF_DIR)/references/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM_REFERENCE)/Microsoft.$(1).xml) $$(abspath $(APIDIFF_DIR)/temp/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).xml) $(APIDIFF_IGNORE) --html "$$(abspath $$(basename $$@).html)" --markdown "$$(abspath $$(basename $$@).md)"
+	$$(QF_GEN) $(MONO_API_HTML_EXEC) $(NEW_REGEX) $(ADD_REGEX) $$(abspath $(APIDIFF_DIR)/references/comparison/Microsoft.$(1).xml) $$(abspath $(APIDIFF_DIR)/references/current/Microsoft.$(1).xml) $(APIDIFF_IGNORE) --html "$$(abspath $$(basename $$@).html)" --markdown "$$(abspath $$(basename $$@).md)"
 	$$(Q) touch $$@
+
+html:: $(OUTPUT_DIR)/diff/Microsoft.$(1).html
+markdown:: $(OUTPUT_DIR)/diff/Microsoft.$(1)%md
 endef
 $(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call DotNetComputeDiff,$(platform))))
 
@@ -97,7 +85,7 @@ $(OUTPUT_DIR)/%-api-diff.html:
 	$(Q) mv $@.temp $@
 	$(Q) rm -f $@-toc
 
-API_DIFF_DEPENDENCIES += $(foreach assembly,$(DOTNET_ASSEMBLIES),$(OUTPUT_DIR)/diff/dotnet/$(assembly).html)
+API_DIFF_DEPENDENCIES += $(foreach platform,$(DOTNET_PLATFORMS),$(OUTPUT_DIR)/diff/Microsoft.$(platform).html)
 
 $(OUTPUT_DIR)/index.html: $(OUTPUT_DIR)/api-diff.html
 	$(Q) $(CP) $< $@
@@ -107,24 +95,24 @@ $(OUTPUT_DIR)/index.html: $(OUTPUT_DIR)/api-diff.html
 #
 
 define ApiDiffReportHtml
-	$(Q) ./report-status.sh "$(1)" "$(OUTPUT_DIR)" html "diff/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).html" "diff/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).md" "$(2)"
+	$(Q) ./report-status.sh "$(1)" "$(OUTPUT_DIR)" html "diff/Microsoft.$(1).html" "diff/Microsoft.$(1).md" "$(2)"
 
 endef
 
 $(OUTPUT_DIR)/api-diff.html: $(API_DIFF_DEPENDENCIES)
 	$(Q) rm -f $@
-	$(QF_GEN) echo "<!DOCTYPE html>" >> $@
-	$(QF_GEN) echo "<html>" >> $@
-	$(QF_GEN) echo "<head>" >> $@
-	$(QF_GEN) echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>' >> $@
-	$(QF_GEN) echo "<title>API diffs</title>" >> $@
-	$(QF_GEN) echo "</head>" >> $@
-	$(QF_GEN) echo "<body>" >> $@
-	$(QF_GEN) echo "<h1>API diffs</h1>" >> $@
+	$(Q) echo "<!DOCTYPE html>" >> $@
+	$(Q) echo "<html>" >> $@
+	$(Q) echo "<head>" >> $@
+	$(Q) echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>' >> $@
+	$(Q) echo "<title>API diffs</title>" >> $@
+	$(Q) echo "</head>" >> $@
+	$(Q) echo "<body>" >> $@
+	$(Q) echo "<h1>API diffs</h1>" >> $@
 
-	$(Q) if $(foreach html,$(wildcard $(OUTPUT_DIR)/diff/dotnet/Microsoft.*.Ref/ref/$(DOTNET_TFM)/Microsoft.*.html),! test -s "$(html)" &&) true; then \
+	$(Q) if $(foreach html,$(wildcard $(OUTPUT_DIR)/diff/Microsoft.*.html),! test -s "$(html)" &&) true; then \
 		echo "<h2>.NET (empty diffs)</h2>" >> "$@"; \
-	elif grep BreakingChangesDetected "$(OUTPUT_DIR)"/diff/dotnet/Microsoft.*.Ref/ref/"$(DOTNET_TFM)"/Microsoft.*.html &> /dev/null; then \
+	elif grep BreakingChangesDetected "$(OUTPUT_DIR)"/diff/Microsoft.*.html &> /dev/null; then \
 		echo "<h2>.NET ($(HTML_BREAKING_CHANGES_MESSAGE))</h2>" >> "$@"; \
 	else \
 		echo "<h2>.NET ($(HTML_NO_BREAKING_CHANGES_MESSAGE))</h2>" >> "$@"; \
@@ -136,8 +124,8 @@ $(OUTPUT_DIR)/api-diff.html: $(API_DIFF_DEPENDENCIES)
 
 	$(Q) echo "</ul>" >> $@
 
-	$(QF_GEN) echo "</body>" >> $@
-	$(QF_GEN) echo "</html>" >> $@
+	$(Q) echo "</body>" >> $@
+	$(Q) echo "</html>" >> $@
 
 	$(Q) if grep "$(HTML_BREAKING_CHANGES_MESSAGE)" $@ >/dev/null 2>&1; then \
 		echo "" >> $@; \
@@ -145,21 +133,23 @@ $(OUTPUT_DIR)/api-diff.html: $(API_DIFF_DEPENDENCIES)
 		echo "" >> $@; \
 	fi
 
+	@echo "Created $@"
+
 #
 # Collect all the diffs into a single api-diff.md file
 #
 
 define ApiDiffReportMarkdown
-	$(Q) ./report-status.sh "$(1)" "$(OUTPUT_DIR)" markdown "diff/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).html" "diff/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).md" "$(2)"
+	$(Q) ./report-status.sh "$(1)" "$(OUTPUT_DIR)" markdown "diff/Microsoft.$(1).html" "diff/Microsoft.$(1).md" "$(2)"
 
 endef
 
 all-markdowns:: $(OUTPUT_DIR)/api-diff.md
 
 $(OUTPUT_DIR)/api-diff.md: $(API_DIFF_DEPENDENCIES)
-	$(Q) if $(foreach html,$(wildcard $(OUTPUT_DIR)/diff/dotnet/Microsoft.*.Ref/ref/$(DOTNET_TFM)/Microsoft.*.html),! test -s "$(html)" &&) true; then \
+	$(Q) if $(foreach html,$(wildcard $(OUTPUT_DIR)/diff/Microsoft.*.html),! test -s "$(html)" &&) true; then \
 		echo "<details><summary>NET (empty diffs)</summary>" >> "$@"; \
-	elif grep BreakingChangesDetected "$(OUTPUT_DIR)"/diff/dotnet/Microsoft.*.Ref/ref/"$(DOTNET_TFM)"/Microsoft.*.html &> /dev/null; then \
+	elif grep BreakingChangesDetected "$(OUTPUT_DIR)"/diff/Microsoft.*.html &> /dev/null; then \
 		echo "<details><summary>.NET ($(MARKDOWN_BREAKING_CHANGES_MESSAGE))</summary>" >> "$@"; \
 	else \
 		echo "<details><summary>.NET ($(MARKDOWN_NO_BREAKING_CHANGES_MESSAGE))</summary>" >> "$@"; \
@@ -186,12 +176,6 @@ all-local:: $(OUTPUT_DIR)/index.html $(OUTPUT_DIR)/api-diff.md
 
 # Rules to re-create the reference infos from the current stable 'bundle.zip' assemblies
 
-# First download the bundle zips we need. Multiple platforms may (or may not) share the same bundle.zip (with the same url),
-# so account for that and only download each bundle.zip once.
-APIDIFF_URLS=$(foreach platform,$(DOTNET_PLATFORMS),$(APIDIFF_REFERENCES_DOTNET_$(platform)))
-APIDIFF_UNIQUE_URLS=$(sort $(APIDIFF_URLS))
-APIDIFF_UNIQUE_HASHES=$(foreach url,$(APIDIFF_UNIQUE_URLS),$(word 5,$(subst /, ,$(url))))
-
 AUTH_TOKEN_GITHUB_COM_FILE=$(HOME)/.config/AUTH_TOKEN_GITHUB_COM
 ifeq ($(AUTH_TOKEN_GITHUB_COM),)
 ifeq ($(AUTH_TOKEN_GITHUB_COM_FILE),$(shell ls -1 $(AUTH_TOKEN_GITHUB_COM_FILE) 2>/dev/null))
@@ -205,53 +189,48 @@ check-token:
 .PHONY: check-token
 
 define DownloadBundle
-BUNDLE_ZIP_$(1)=$(APIDIFF_DIR)/bundle-$(1).zip
-BUNDLE_ZIP_$(1)_URL=$(shell echo $(APIDIFF_UNIQUE_URLS) | tr ' ' '\n' | grep '/$(1)/')
+BUNDLE_ZIP_$(1)=$(APIDIFF_DIR)/Microsoft.$(1).Ref.$(STABLE_NUGET_VERSION_$(1)).nupkg
+STABLE_NUGET_$(1)_URL=https://www.nuget.org/api/v2/package/Microsoft.$(1).Ref.$(STABLE_NUGET_VERSION_$(1))
+CACHE_FILE_$(1)=~/Library/Caches/xamarin-macios/Microsoft.$(1).Ref.$(STABLE_NUGET_VERSION_$(1)).nupkg
 $$(BUNDLE_ZIP_$(1)):
 	$(Q) mkdir -p $$(dir $$@)
 	@# download to a temporary filename so interrupted downloads won't prevent re-downloads.
-	@echo "Downloading $$(BUNDLE_ZIP_$(1)_URL)..."
-	$$(Q) if test -f ~/Library/Caches/xamarin-macios/$$(notdir $$@); then \
-		echo "Found a cached version of $$(notdir $$@) in ~/Library/Caches/xamarin-macios/$$(notdir $$@)."; \
-		$$(CP) ~/Library/Caches/xamarin-macios/$$(notdir $$@) $$@.tmp; \
+	@echo "Downloading $$(STABLE_NUGET_$(1)_URL)..."
+	$$(Q) if test -f $$(CACHE_FILE_$(1)); then \
+		echo "Found a cached version: $$(CACHE_FILE_$(1))."; \
+		$$(CP) $$(CACHE_FILE_$(1)) $$@.tmp; \
 	else \
 		$(MAKE) check-token || exit 1; \
-		if ! $(CURL_RETRY) -H "Authorization: token $(AUTH_TOKEN_GITHUB_COM)" "$$(BUNDLE_ZIP_$(1)_URL)" --output $$@.tmp; then \
-			echo "Failed to download $$(BUNDLE_ZIP_$(1)_URL)"; \
+		if ! $(CURL_RETRY) -H "Authorization: token $(AUTH_TOKEN_GITHUB_COM)" "$$(STABLE_NUGET_$(1)_URL)" --output $$@.tmp; then \
+			echo "Failed to download $$(STABLE_NUGET_$(1)_URL)"; \
 			exit 1; \
 		fi; \
 		if [[ "x$$$$MACIOS_CACHE_DOWNLOADS" != "x" ]]; then \
-			mkdir -p ~/Library/Caches/xamarin-macios/; \
-			$$(CP) $$@.tmp ~/Library/Caches/xamarin-macios/"$$(notdir $$@)"; \
-			echo "Cached the download of $$(notdir $$@) in ~/Library/Caches/xamarin-macios"; \
+			mkdir -p $$(dir $$(CACHE_FILE_$(1))); \
+			$$(CP) $$@.tmp $$(CACHE_FILE_$(1)); \
+			echo "Cached the download in $$(CACHE_FILE_$(1))"; \
 		fi; \
 	fi
 	$$(Q) mv $$@.tmp $$@
 
-BUNDLE_ZIPS+=$$(BUNDLE_ZIP_$(1))
+download:: $$(BUNDLE_ZIP_$(1))
 endef
-$(foreach hash,$(APIDIFF_UNIQUE_HASHES),$(eval $(call DownloadBundle,$(hash))))
+$(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call DownloadBundle,$(platform))))
 
-download: $(BUNDLE_ZIPS)
-
-# Here we unzip the downloaded bundle.
+# Here we unzip the downloaded nupkg
 define UnzipBundle
-UNZIP_STAMP_$(1)=$(APIDIFF_DIR)/.unzip.$(1).stamp
-UNZIP_DIR_$(1)=temp/downloads/$(1)
-$$(UNZIP_STAMP_$(1)): $$(BUNDLE_ZIP_$(1))
+ifndef COMPARISON_DLL_$(1)
+UNZIP_DIR_$(1)=temp/comparison/$(1)
+COMPARISON_DLL_$(1)=$$(UNZIP_DIR_$(1))/Microsoft.$(1).dll
+$$(COMPARISON_DLL_$(1)): $$(BUNDLE_ZIP_$(1))
 	$$(Q) rm -Rf "$$(UNZIP_DIR_$(1))"
 	$$(Q) mkdir -p $$(dir $$(UNZIP_DIR_$(1)))
-	$$(Q_GEN) unzip $$(if $$(V),,-q) -d $$(UNZIP_DIR_$(1)) $$<
-	$$(Q) touch $$@
+	$$(Q_GEN) unzip -j $$(if $$(V),,-q) -d $$(UNZIP_DIR_$(1)) $$< 'ref/*/Microsoft.$(1).dll'
+endif
 
-# the semi-colon at the end means an empty recipe, and is required for make to consider pattern rules
-$$(UNZIP_DIR_$(1))/%.dll: $$(UNZIP_STAMP_$(1)) ;
-
-UNZIP_STAMPS+=$$(UNZIP_STAMP_$(1))
+unzip:: $$(COMPARISON_DLL_$(1))
 endef
-$(foreach hash,$(APIDIFF_UNIQUE_HASHES),$(eval $(call UnzipBundle,$(hash))))
-
-unzip: $(UNZIP_STAMPS)
+$(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call UnzipBundle,$(platform))))
 
 define DotNetUnzipDirectory
 APIDIFF_HASH_DOTNET_$(1)=$$(word 5,$$(subst /, ,$$(APIDIFF_REFERENCES_DOTNET_$(1))))
@@ -259,28 +238,26 @@ UNZIP_DIR_DOTNET_$(1)=$$(UNZIP_DIR_$$(APIDIFF_HASH_DOTNET_$(1)))
 endef
 $(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call DotNetUnzipDirectory,$(platform))))
 
-DOTNET_REFS = $(foreach file,$(DOTNET_ASSEMBLIES),$(APIDIFF_DIR)/updated-references/dotnet/$(file).xml)
-
-define DotNetGenerateReferenceXml
-$(APIDIFF_DIR)/references/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM_REFERENCE)/Microsoft.$(1).xml: $(UNZIP_DIR_DOTNET_$(1))/Microsoft.$(1).Ref/ref/$(DOTNET_TFM_REFERENCE)/Microsoft.$(1).dll  $(MONO_API_INFO)
+define GenerateComparisonReferenceXml
+$(APIDIFF_DIR)/references/comparison/Microsoft.$(1).xml: $$(COMPARISON_DLL_$(1)) $(MONO_API_INFO)
 	$$(Q) mkdir -p $$(dir $$@)
 	$$(QF_GEN) $(MONO_API_INFO_EXEC) $$(abspath $$<) -o $$(abspath $$@)
+
+update-comparison-refs:: $(APIDIFF_DIR)/references/comparison/Microsoft.$(1).xml
 endef
-$(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call DotNetGenerateReferenceXml,$(platform))))
+$(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call GenerateComparisonReferenceXml,$(platform))))
 
-define UpdatedReferences
-$(APIDIFF_DIR)/updated-references/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).xml: $(DOTNET_DESTDIR)/$($(1)_NUGET_REF_NAME)/ref/$(DOTNET_TFM)/Microsoft.$(1).dll $(MONO_API_INFO)
-	$$(Q) mkdir -p $$(dir $$@) $$(dir $$(APIDIFF_DIR)/references/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).Ref)
-	$$(QF_GEN) $$(MONO_API_INFO_EXEC) $$(abspath $$<) -o $$(abspath $$(APIDIFF_DIR)/references/dotnet/Microsoft.$(1).Ref/ref/$(DOTNET_TFM)/Microsoft.$(1).xml)
+define GenerateCurrentReferenceXml
+$(APIDIFF_DIR)/references/current/Microsoft.$(1).xml: $(DOTNET_DESTDIR)/$($(1)_NUGET_REF_NAME)/ref/$(DOTNET_TFM)/Microsoft.$(1).dll $(MONO_API_INFO)
+	$$(Q) mkdir -p $$(dir $$@)
+	$$(QF_GEN) $$(MONO_API_INFO_EXEC) $$(abspath $$<) -o $$(abspath $$@)
+
+update-current-refs:: $(APIDIFF_DIR)/references/current/Microsoft.$(1).xml
 endef
-
-$(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call UpdatedReferences,$(platform))))
-
-update-dotnet: $(DOTNET_REFS)
-update-refs: $(DOTNET_REFS)
+$(foreach platform,$(DOTNET_PLATFORMS),$(eval $(call GenerateCurrentReferenceXml,$(platform))))
 
 clean-local::
-	rm -rf temp references updated-references diff dotnet *.exe* api-diff.html
+	rm -rf temp references diff dotnet *.exe* api-diff.html
 	rm -rf *.dll* bundle-*.zip $(UNZIP_STAMPS)
 	rm -rf ios-*.md tvos-*.md watchos-*.md macos-*.md dotnet-*.md
 
