[CI] Perform the classic sign-notarize of each pkg in parallel.

diff --git a/tools/devops/automation/templates/sign-and-notarized/funnel.yml b/tools/devops/automation/templates/sign-and-notarized/funnel.yml
--- a/tools/devops/automation/templates/sign-and-notarized/funnel.yml
+++ b/tools/devops/automation/templates/sign-and-notarized/funnel.yml
@@ -1,4 +1,8 @@
 # funnel job that will download all the signed artifacts and puts them in the final location
+parameters:
+- name: packages
+  type: object
+
 steps:
 
 # DO NOT USE THE checkout.yml template. The reason is that the template changes the hash which results in a problem with the artifacts scripts
@@ -17,19 +21,41 @@ steps:
 - checkout: release-scripts
   clean: true
 
+- bash: |
+    mkdir -p $(Build.SourcesDirectory)/package/notarized
+  displayName: 'Create target directories.'
+
 - task: DownloadPipelineArtifact@2
-  displayName: Download not notarized build
+  displayName: Download notaraized build dotnet
   inputs:
     artifact: 'dotnet-signed'
     allowFailedBuilds: true
     path: $(Build.SourcesDirectory)/package
 
-- task: DownloadPipelineArtifact@2
-  displayName: Download not notarized build
-  inputs:
-    artifact: 'classic-signed'
-    allowFailedBuilds: true
-    path: $(Build.SourcesDirectory)/package
+- ${{ each pkg in parameters.packages }}:
+  - task: DownloadPipelineArtifact@2
+    displayName: Download notaraized build ${{ pkg.name }}
+    inputs:
+      artifact: 'classic-${{ pkg.name }}-signed'
+      allowFailedBuilds: true
+      path: '$(Build.SourcesDirectory)/classic-${{ pkg.name }}-signed'
+
+  - bash: |
+      set -x
+      set -e
+
+      ls -lR $(Build.SourcesDirectory)
+
+      FULL_PATH="$(Build.SourcesDirectory)/classic-${{ pkg.name }}-signed"
+      PACKAGES=$(find . f -name "${{ pkg.pattern }}" | xargs basename)
+      if [ -z "$PACKAGES" ]; then
+        echo "Packages ${{ parameters.packageName }} not found."
+      else
+        cp "$FULL_PATH/$PACKAGES" "$(Build.SourcesDirectory)/package"
+        cp "$FULL_PATH/notarized/$PACKAGES" "$(Build.SourcesDirectory)/package/notarized"
+      fi
+    displayName: 'Move pkg ${{ pkg.name }} to its final destination'
+
 
 - template: generate-workspace-info.yml@templates
   parameters:
