Run simulator tests in the same job we build the pkgs.

diff --git a/tools/devops/automation/templates/build-packages.yml b/tools/devops/automation/templates/build-packages.yml
--- a/tools/devops/automation/templates/build-packages.yml
+++ b/tools/devops/automation/templates/build-packages.yml
@@ -250,3 +250,78 @@ steps:
     targetPath: $(Build.SourcesDirectory)/xamarin-macios/tests/*.7z
     artifactName: package-internal
   continueOnError: true
+
+- bash: |
+    if ! test -f ~/Library/Keychains/"$KEYCHAIN".keychain-db; then
+      echo "The '$KEYCHAIN' keychain is not available."
+      exit 1
+    fi
+    security default-keychain -s "$KEYCHAIN.keychain"
+    security list-keychains -s "$KEYCHAIN.keychain"
+    echo "Unlock keychain"
+
+    security unlock-keychain -p "$OSX_KEYCHAIN_PASS"
+    echo "Increase keychain unlock timeout to 6 hours"
+    security set-keychain-settings -lut 21600
+    security -v find-identity "$KEYCHAIN.keychain"
+
+    echo "Remove UI prompt"
+    security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$OSX_KEYCHAIN_PASS" "$KEYCHAIN.keychain" >/dev/null 2>&1
+  env:
+    OSX_KEYCHAIN_PASS: $(OSX_KEYCHAIN_PASS)
+    KEYCHAIN: 'xamarin-macios'
+  displayName: 'Remove security UI-prompt for tests (http://stackoverflow.com/a/40039594/183422)'
+
+- bash:
+    rm -rf ~/.config/.mono/keypairs/
+
+    RC=0
+    make -C tests "$TARGET" || RC=$?
+
+    if [[ x$RC != x0 ]]; then
+      exit $RC
+    fi
+
+    if test -f "$WORKSPACE/jenkins/failure-stamp"; then
+      echo "Something went wrong:"
+      cat "$WORKSPACE/jenkins/pr-comments.md"
+      exit 1
+    fi
+  displayName: 'Run tests'
+  timeoutInMinutes: 600
+  condition: succeededOrFailed() # we do not care about the previous process cleanup
+  env:
+    BUILD_REVISION: jenkins
+    KEYCHAIN_PWD_FILE: '~/.config/keychain'
+    KEYCHAIN: 'xamarin-macios'
+    TARGET: 'wrench-jenkins'
+
+# Upload TestSummary as an artifact.
+- task: PublishPipelineArtifact@1
+  displayName: 'Publish Artifact: TestSummary'
+  inputs:
+    targetPath: 'xamarin-macios/tests/TestSummary.md'
+    artifactName: TestSummary
+  continueOnError: true
+  condition: succeededOrFailed()
+
+# Archive files for the Html Report so that the report can be easily uploaded as artifacts of the build.
+- task: ArchiveFiles@1
+  displayName: 'Archive HtmlReport'
+  inputs:
+    rootFolder: 'xamarin-macios/jenkins-results'
+    includeRootFolder: false
+    archiveFile: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
+  continueOnError: true
+  condition: succeededOrFailed()
+
+# Create HtmlReport artifact. This serves two purposes:
+# 1. It is the way we are going to share the HtmlReport with the publish_html job that is executed on a Windows machine.
+# 2. Users can download this if they want.
+- task: PublishPipelineArtifact@1
+  displayName: 'Publish Artifact: HtmlReport'
+  inputs:
+    targetPath: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
+    artifactName: HtmlReport
+  continueOnError: true
+  condition: succeededOrFailed()
