[VSTS] Start running tests on the pipeline (#10116)
Adds the following:

* governance tests
* simulator tests
* device tests
  - iOS
  - iOS32
  - tvOS

The results are not yet really adding a nice message at the end. There are a few things to fix

* When build gets canceled, cancel all device tests.
* If signing the pkgs fails, set a status and report it.
* Add github comment with the test results.
* Get and propagate the test labels.

diff --git a/tools/devops/automation/templates/build-packages.yml b/tools/devops/automation/templates/build-packages.yml
--- a/tools/devops/automation/templates/build-packages.yml
+++ b/tools/devops/automation/templates/build-packages.yml
@@ -24,6 +24,14 @@ steps:
   displayName: 'Remove security UI-prompt (http://stackoverflow.com/a/40039594/183422)'
   condition: succeededOrFailed() # we do not care about the previous process cleanup
 
+- template: install-certificates.yml@templates
+  parameters:
+    DeveloperIdApplication: $(developer-id-application)
+    DeveloperIdInstaller: $(developer-id-installer)
+    IphoneDeveloper: $(iphone-developer)
+    MacDeveloper: $(mac-developer)
+    HostedMacKeychainPassword: $(OSX_KEYCHAIN_PASS)
+
 - task: xamops.azdevex.provisionator-task.provisionator@2
   displayName: 'Provision Brew components'
   inputs:
@@ -74,7 +82,6 @@ steps:
     time make -C $(Build.SourcesDirectory)/xamarin-macios/ git-clean-all
   displayName: 'Clear results directory'
   timeoutInMinutes: 5
-
 
 # the following should be using the labels in the PR, we are not yet doing so, but we will in the
 # future
@@ -176,27 +183,8 @@ steps:
   displayName: 'Signing PR Build'
   condition: and(succeeded(), eq(variables['configuration.SignPkgs'], 'True'), eq(variables['configuration.IsPr'], 'True'))
 
-# UNDONE: This step can be removed once the agents have been sanitized
-- template: uninstall-certificates/v1.yml@templates
-  parameters:
-    HostedMacKeychainPassword: $(OSX_KEYCHAIN_PASS)
-
-- template: install-certificates.yml@templates
-  parameters:
-    DeveloperIdApplication: $(developer-id-application)
-    DeveloperIdInstaller: $(developer-id-installer)
-    IphoneDeveloper: $(iphone-developer)
-    MacDeveloper: $(mac-developer)
-    HostedMacKeychainPassword: $(OSX_KEYCHAIN_PASS)
-
-# HACK HACK: brew remove python2, but the script uses python2, this is a dirty workaround
 - bash: |
-    wget https://raw.githubusercontent.com/Homebrew/homebrew-core/86a44a0a552c673a05f11018459c9f5faae3becc/Formula/python@2.rb
-    brew install python@2.rb
-    rm python@2.rb
-  displayName: 'Install Python 2 and pip'
-
-- bash: |
+    export PATH="$PATH:/Users/builder/Library/Python/2.7/bin"  # UNDONE: Temporary fix until virtualenv is included in the image along with the PATH setting
     VIRTUAL_ENV_PATH=$(Build.SourcesDirectory)/venv
     pip install virtualenv
     virtualenv "$VIRTUAL_ENV_PATH" --system-site-packages
@@ -212,7 +200,7 @@ steps:
     deactivate
     rm -Rf "$VIRTUAL_ENV_PATH"
   env:
-    PRODUCTSIGN_KEYCHAIN_PASSWORD: $(AzDO-OnPrem-KeychainPass)
+    PRODUCTSIGN_KEYCHAIN_PASSWORD: $(OSX_KEYCHAIN_PASS)
     MAC_ENTITLEMENTS: $(Build.SourcesDirectory)/xamarin-macios/mac-entitlements.plist
     APP_ID: $(XamarinAppId)
     INSTALL_ID: $(XamarinAppId)
@@ -248,3 +236,79 @@ steps:
     targetPath: $(Build.SourcesDirectory)/package-internal 
     artifactName: package-internal
   continueOnError: true
+
+- bash:
+    set -x
+    set -e
+
+    make -C $(Build.SourcesDirectory)/xamarin-macios/tests package-tests
+  displayName: 'Package Xamarin.mac tests'
+  continueOnError: true # not a terrible blocking issue
+
+- task: PublishPipelineArtifact@1
+  displayName: 'Publish Xamarin.Mac tests'
+  inputs:
+    targetPath: $(Build.SourcesDirectory)/xamarin-macios/tests/*.7z
+    artifactName: package-internal
+  continueOnError: true
+
+- bash:
+    rm -rf ~/.config/.mono/keypairs/
+
+    RC=0
+    make -C $(Build.SourcesDirectory)/xamarin-macios/tests "$TARGET" || RC=$?
+
+    if [ $RC -eq 0 ]; then
+      echo '##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Succeeded'
+    else
+      echo '##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Failed'
+    fi
+
+    if test -f "$(Build.SourcesDirectory)/xamarin-macios//jenkins/failure-stamp"; then
+      echo "Something went wrong:"
+      cat "$(Build.SourcesDirectory)/xamarin-macios//jenkins/pr-comments.md"
+      exit 1
+    fi
+  displayName: 'Run tests'
+  name: runTests # not to be confused with the displayName, this is used to later use the name of the step to access the output variables from an other job
+  timeoutInMinutes: 600
+  condition: succeededOrFailed() # we do not care about the previous process cleanup
+  env:
+    BUILD_REVISION: jenkins
+    TARGET: 'wrench-jenkins'
+
+# Upload TestSummary as an artifact.
+- task: PublishPipelineArtifact@1
+  displayName: 'Publish Artifact: TestSummary'
+  inputs:
+    targetPath: 'xamarin-macios/tests/TestSummary.md'
+    artifactName: TestSummary
+  continueOnError: true
+  condition: succeededOrFailed()
+
+- pwsh: |
+    summaryName = "TestSummary.md"
+    summaryPath = "$Env:SYSTEM_DEFAULTWORKINGDIRECTORY/xamarin-macios/tests/TestSummary.md"
+    Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=$summaryName;]$summaryPath"
+  displayName: Set TestSummary
+
+# Archive files for the Html Report so that the report can be easily uploaded as artifacts of the build.
+- task: ArchiveFiles@1
+  displayName: 'Archive HtmlReport'
+  inputs:
+    rootFolder: 'xamarin-macios/jenkins-results'
+    includeRootFolder: false
+    archiveFile: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
+  continueOnError: true
+  condition: succeededOrFailed()
+
+# Create HtmlReport artifact. This serves two purposes:
+# 1. It is the way we are going to share the HtmlReport with the publish_html job that is executed on a Windows machine.
+# 2. Users can download this if they want.
+- task: PublishPipelineArtifact@1
+  displayName: 'Publish Artifact: HtmlReport'
+  inputs:
+    targetPath: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
+    artifactName: HtmlReport
+  continueOnError: true
+  condition: succeededOrFailed()
