[Devops] If we fail to provision dependencies skip certain tasks.
xamarin-storage can not be reachable or a network issue might happen
when we try to provision the dependencies. In that case, skip those
tasks that are skipped when we cannot provision the certs.

The provisioning dependencies will only execute in the provisioning
profiles was successful, therefore, the if statement is not stepping in
any value that was set by the profiles step.

diff --git a/tools/devops/device-tests-common.yml b/tools/devops/device-tests-common.yml
--- a/tools/devops/device-tests-common.yml
+++ b/tools/devops/device-tests-common.yml
@@ -65,9 +65,9 @@ jobs:
 
       ./maccore/tools/install-qa-provisioning-profiles.sh -v
       if [ $? -eq 0 ]; then
-        echo "##vso[task.setvariable variable=ProvisioningProfiles]success"
+        echo "##vso[task.setvariable variable=ProvisioningStatus]success"
       else
-        echo "##vso[task.setvariable variable=ProvisioningProfiles]failure"
+        echo "##vso[task.setvariable variable=ProvisioningStatus]failure"
       fi
     displayName: 'Add provisioning profiles'
     env:
@@ -78,6 +78,11 @@ jobs:
       set -e
 
       ./xamarin-macios/system-dependencies.sh --ignore-all --provision-xcode --provision-xamarin-studio --provision-mono --provision-7z
+      if [ $? -eq 0 ]; then
+        echo "##vso[task.setvariable variable=ProvisioningStatus]success"
+      else
+        echo "##vso[task.setvariable variable=ProvisioningStatus]failure"
+      fi
     displayName: 'Provision dependencies'
     timeoutInMinutes: 240
 
@@ -149,7 +154,7 @@ jobs:
   - bash: ./xamarin-macios/tools/devops/add-summaries.sh
     displayName: 'Add summaries'
     continueOnError: true
-    condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success')) # if profiles did not succeded we do not need to do a thing since we have no summaries
+    condition: and(succeededOrFailed(), eq(variables['ProvisioningStatus'], 'success')) # if profiles did not succeded we do not need to do a thing since we have no summaries
 
   - task: ArchiveFiles@1
     displayName: 'Archive HtmlReport'
@@ -158,7 +163,7 @@ jobs:
       includeRootFolder: false
       archiveFile: '$(Build.ArtifactStagingDirectory)/HtmlReport-$(Build.BuildId).zip'
     continueOnError: true
-    condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success')) # if profiles did not succeded we do not need to do a thing since we have no summaries
+    condition: and(succeededOrFailed(), eq(variables['ProvisioningStatus'], 'success')) # if profiles did not succeded we do not need to do a thing since we have no summaries
 
   ###
   ### Upload the xml results to vsts. We have two types, nunit and xunit. We want both
@@ -171,7 +176,7 @@ jobs:
       testResultsFiles: '**/vsts-*.xml'
       failTaskOnFailedTests: true
     continueOnError: true
-    condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success')) # with no profiles we have no test results
+    condition: and(succeededOrFailed(), eq(variables['ProvisioningStatus'], 'success')) # with no profiles we have no test results
 
   ###
   ### Push the HTML report to Azure DevOps (shows up in Summary tab as Build Artifact)
@@ -183,7 +188,7 @@ jobs:
       pathtoPublish: '$(Build.ArtifactStagingDirectory)/HtmlReport-$(Build.BuildId).zip'
       artifactName: HtmlReport
     continueOnError: true
-    condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success')) # with no profiles we have no test results
+    condition: and(succeededOrFailed(), eq(variables['ProvisioningStatus'], 'success')) # with no profiles we have no test results
 
   ###
   ### Cleanup after us, not having that can lead to VSMac install issues
