set TestState to failure before we try to run tests, add partial provisioning improvements

diff --git a/tools/devops/templates/device-tests.yml b/tools/devops/templates/device-tests.yml
--- a/tools/devops/templates/device-tests.yml
+++ b/tools/devops/templates/device-tests.yml
@@ -31,7 +31,14 @@ steps:
     rm -f ~/Library/Caches/com.xamarin.provisionator/Provisions/*p12
     rm -f ~/Library/Caches/com.xamarin.provisionator/Provisions/*mobileprovision
 
-    ./maccore/tools/install-qa-provisioning-profiles.sh -v
+    EC=0
+    ./maccore/tools/install-qa-provisioning-profiles.sh -v || EC=$?
+    if [ $EC -eq 0 ]; then
+      echo "##vso[task.setvariable variable=ProvisioningProfiles]success"
+    else
+      echo "##vso[task.setvariable variable=ProvisioningProfiles]failure"
+    fi
+    exit $EC
   displayName: 'Add provisioning profiles'
   env:
     LOGIN_KEYCHAIN_PASSWORD: $(OSX_KEYCHAIN_PASS)
@@ -47,12 +54,13 @@ steps:
     if grep ignore-python3 xamarin-macios/system-dependencies.sh 2>&1 > /dev/null; then
         CONFIGURE_ARGS="$CONFIGURE_ARGS --ignore-python3"
     fi
-    ./xamarin-macios/system-dependencies.sh $CONFIGURE_ARGS
-    if [ $? -eq 0 ]; then
+    ./xamarin-macios/system-dependencies.sh $CONFIGURE_ARGS || EC=$?
+    if [ $EC -eq 0 ]; then
       echo "##vso[task.setvariable variable=ProvisioningProfiles]success"
     else
       echo "##vso[task.setvariable variable=ProvisioningProfiles]failure"
     fi
+    exit $EC
   displayName: 'Provision dependencies'
   timeoutInMinutes: 240
 
@@ -89,10 +97,19 @@ steps:
   displayName: 'Fix device discovery (reset launchctl)'
 
 ###
+### Always set TestState to failure. If tests are skipped we do not want to have TestState == null.
+###
+- bash: |
+    set -x
+    set -e
+
+    echo "##vso[task.setvariable variable=TestState]failure"
+  displayName: 'Set TestState to failure before trying to run tests'
+  condition: succeededOrFailed()
+
+###
 ### Run the device tests
 ###
-
-  # move this to in-line code, should be very short
 - bash: |
     set -x
     set -e
@@ -122,7 +139,7 @@ steps:
       echo ":fire: Tests failed catastrophically (no summary found)" > $FILE
       echo "##vso[task.setvariable variable=TestState]failure"
     fi
-  displayName: "If test summary does not exist, create test summary"
+  displayName: "Check for test summary, if does not exist create test summary"
   condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success'))
 
 ###
