try out setting var in a bash task

diff --git a/tools/devops/templates/device-tests.yml b/tools/devops/templates/device-tests.yml
--- a/tools/devops/templates/device-tests.yml
+++ b/tools/devops/templates/device-tests.yml
@@ -95,6 +95,32 @@ steps:
   displayName: 'Run tests'
   timeoutInMinutes: 600
 
+- bash: |
+    echo "##vso[task.setvariable variable=TestState]failure"
+    echo "$(TestState)"
+  displayName: "set github status to failure if run-tests failed"
+  condition: failed()
+
+#- variables:
+#  github.status: "success"
+
+#variables:
+#  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: # only works if you have a master branch
+#    stageName: prod
+
+# - bash: |
+#     set -e
+#     set -x
+#     echo "success!"
+#   displayName: 'Success!!'
+#   condition: eq(variables['TESTSTATE'], 'success'))
+
+# - bash: |
+#     set -e
+#     set -x
+#     echo "failure!"
+#   displayName: 'Failure!!'
+#   condition: eq(variables['TESTSTATE'], 'failure'))
 
 - bash: ./xamarin-macios/tools/devops/add-summaries.sh
   displayName: 'Add summaries'
