first try at adding test summary to per-test failure comment, moved when test summaries get published to vsts as artifacts

diff --git a/tools/devops/templates/device-tests.yml b/tools/devops/templates/device-tests.yml
--- a/tools/devops/templates/device-tests.yml
+++ b/tools/devops/templates/device-tests.yml
@@ -95,6 +95,28 @@ steps:
   displayName: 'Run tests'
   timeoutInMinutes: 600
 
+  ###
+  ### If test summary does not exist, create test summary files so that we can notify
+  ### that no results were published at the per-test AND final results steps
+  ###
+- bash: |
+    set -e
+    set -x
+    FILE="TestSummary-${CONTEXT}.md"
+    echo $FILE
+    if ! test -f $FILE; then
+    echo ":fire: Tests failed catastrophically (no summary found)" > $FILE
+    fi
+  displayName: "If test summary not found, create test summary"
+
+- task: PublishPipelineArtifact@1
+  displayName: 'Publish Artifact: TestSummary'
+  inputs:
+#    targetPath: 'xamarin-macios/tests/TestSummary.md'
+    targetPath: TestSummary-$(CONTEXT).md
+    artifactName: TestSummary-$(CONTEXT)
+  continueOnError: true
+#  condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success'))
 
 # if there's a failure:
 # - update GH commit status
@@ -103,7 +125,7 @@ steps:
 # pwsh for PowerShell Core
 # powershell is for Win only PowerShell
 - pwsh: ./xamarin-macios/tools/devops/templates/publish_failure.ps1
-  condition: failed()
+#  condition: failed()
   env:
     BUILD_REVISION: $(BUILD_REVISION)
     GH_STATE: $(GH_STATE)
@@ -143,8 +165,8 @@ steps:
 ###
 ### Push the HTML report to Azure DevOps (shows up in Summary tab as Build Artifact)
 ###
-- bash: |
-    echo "$CONTEXT" >> TestSummary-$CONTEXT.md
+#- bash: |
+#    echo "$CONTEXT" >> TestSummary-$CONTEXT.md
 
 - task: PublishPipelineArtifact@1
   displayName: 'Publish Artifact: HtmlReport'
@@ -154,14 +176,6 @@ steps:
   continueOnError: true
   condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success'))
 
-- task: PublishPipelineArtifact@1
-  displayName: 'Publish Artifact: TestSummary'
-  inputs:
-#    targetPath: 'xamarin-macios/tests/TestSummary.md'
-    targetPath: TestSummary-$(CONTEXT).md
-    artifactName: TestSummary-$(CONTEXT)
-  continueOnError: true
-#  condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success'))
 
 ###
 ### Cleanup after us, not having that can lead to VSMac install issues
