add step for test summary if provisioning fails, fix summary path in publish_failure

diff --git a/tools/devops/templates/device-tests.yml b/tools/devops/templates/device-tests.yml
--- a/tools/devops/templates/device-tests.yml
+++ b/tools/devops/templates/device-tests.yml
@@ -111,6 +111,19 @@ steps:
   displayName: "If test summary not found, create test summary"
   condition: and(succeededOrFailed(), eq(variables['ProvisioningProfiles'], 'success'))
 
+### TODO: can probably figure out way to do this in the bash script above for
+### test failures
+### If provisioning failed, create test summary files to indicate failure
+###
+- bash: |
+    set -e
+    set -x
+    FILE="TestSummary-${CONTEXT}.md"
+    echo $FILE
+    echo ":fire: Provisioning step failed" > $FILE
+  displayName: 'Add test summary for failed provisioning'
+  condition: eq(variables['ProvisioningProfiles'], 'failure')
+
 - task: PublishPipelineArtifact@1
   displayName: 'Publish Artifact: TestSummary'
   inputs:
