[CI] Check that the mac tests are indeed present.

diff --git a/tools/devops/automation/templates/build/build.yml b/tools/devops/automation/templates/build/build.yml
--- a/tools/devops/automation/templates/build/build.yml
+++ b/tools/devops/automation/templates/build/build.yml
@@ -432,7 +432,15 @@ steps:
     set -x
     set -e
 
-    make -C $(Build.SourcesDirectory)/xamarin-macios/tests package-tests
+    RC=0
+    make -C $(Build.SourcesDirectory)/xamarin-macios/tests package-tests || RC=$?
+    if [ $RC -eq 0 ]; then
+      echo "##vso[task.setvariable variable=macTestsPresent;isOutput=true]Succeeded"
+    else
+      echo "##vso[task.setvariable variable=macTestsPresent;isOutput=true]Failed"
+    fi
+    
+  name: macTestPkg
   displayName: 'Package Xamarin.mac tests'
   condition: and(succeeded(), contains(variables['configuration.RunMacTests'], 'True'))
   continueOnError: true # not a terrible blocking issue
