Remove even more steps.

diff --git a/tools/devops/automation/templates/build/build.yml b/tools/devops/automation/templates/build/build.yml
--- a/tools/devops/automation/templates/build/build.yml
+++ b/tools/devops/automation/templates/build/build.yml
@@ -35,6 +35,10 @@ parameters:
   type: boolean
   default: true
 
+- name: skipPackages
+  type: boolean
+  default: false 
+
 steps:
 - checkout: self          # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout
   clean: true             # Executes: git clean -ffdx && git reset --hard HEAD
@@ -376,21 +380,23 @@ steps:
     parameters:
       prID: variables['PrID']
 
-# build not signed .pkgs for the SDK
-- bash: |
-    set -x
-    set -e
-    rm -Rf $(Build.SourcesDirectory)/package/*.pkg
-    rm -Rf $(Build.SourcesDirectory)/package/notarized/*.pkg
-    time make -C $(Build.SourcesDirectory)/xamarin-macios/ package
-  name: packages
-  displayName: 'Build Packages'
-  condition: and(succeeded(), contains(variables['configuration.BuildPkgs'], 'True'))
-  timeoutInMinutes: 180
 
-# build nugets
-- ${{ if eq(parameters.enableDotnet, true) }}:
-  - template: build-nugets.yml
+- ${{ if ne(parameters.skipPackages, true) }}:
+  # build not signed .pkgs for the SDK
+  - bash: |
+      set -x
+      set -e
+      rm -Rf $(Build.SourcesDirectory)/package/*.pkg
+      rm -Rf $(Build.SourcesDirectory)/package/notarized/*.pkg
+      time make -C $(Build.SourcesDirectory)/xamarin-macios/ package
+    name: packages
+    displayName: 'Build Packages'
+    condition: and(succeeded(), contains(variables['configuration.BuildPkgs'], 'True'))
+    timeoutInMinutes: 180
+
+  # build nugets
+  - ${{ if eq(parameters.enableDotnet, true) }}:
+    - template: build-nugets.yml
 
 
 - ${{ if eq(parameters.signAndNotarize, true) }}:
@@ -404,163 +410,165 @@ steps:
 - ${{ if eq(parameters.enableDotnet, true) }}:
   - template: publish-nugets.yml
 
-- template: generate-workspace-info.yml@templates
-  parameters:
-    GitHubToken: $(GitHub.Token)
-    ArtifactDirectory: $(Build.SourcesDirectory)/package-internal
+- ${{ if ne(parameters.skipPackages, true) }}:
+  - template: generate-workspace-info.yml@templates
+    parameters:
+      GitHubToken: $(GitHub.Token)
+      ArtifactDirectory: $(Build.SourcesDirectory)/package-internal
 
-# upload each of the pkgs into the pipeline artifacts
-- task: PublishPipelineArtifact@1
-  displayName: 'Publish Build Artifacts'
-  inputs:
-    targetPath: $(Build.SourcesDirectory)/package
-    artifactName: package
-  continueOnError: true
+  # upload each of the pkgs into the pipeline artifacts
+  - task: PublishPipelineArtifact@1
+    displayName: 'Publish Build Artifacts'
+    inputs:
+      targetPath: $(Build.SourcesDirectory)/package
+      artifactName: package
+    continueOnError: true
 
-- task: PublishPipelineArtifact@1
-  displayName: 'Publish Build Internal Artifacts'
-  inputs:
-    targetPath: $(Build.SourcesDirectory)/package-internal
-    artifactName: package-internal
-  continueOnError: true
+  - task: PublishPipelineArtifact@1
+    displayName: 'Publish Build Internal Artifacts'
+    inputs:
+      targetPath: $(Build.SourcesDirectory)/package-internal
+      artifactName: package-internal
+    continueOnError: true
 
-# funny enough we need these profiles to build the mac tests
-- bash: |
-    set -x
-    set -e
+  # funny enough we need these profiles to build the mac tests
+  - bash: |
+      set -x
+      set -e
 
-    cd "$SOURCES_DIR/maccore/tools/"
-    ./install-qa-provisioning-profiles.sh -v
-  displayName: 'Add tests provisioning profiles'
-  timeoutInMinutes: 30
-  continueOnError: true # should not stop the build will result in test failures but we do want the pkg
-  env:
-    AUTH_TOKEN_GITHUB_COM: ${{ parameters.gitHubToken }}
-    AUTH_TOKEN_LA_DEV_APPLE_P12: ${{ parameters.xqaCertPass }}
-    AUTH_TOKEN_LA_DISTR_APPLE_P12: ${{ parameters.xqaCertPass }}
-    AUTH_TOKEN_LA_MAC_INSTALLER_DISTR_P12: ${{ parameters.xqaCertPass }}
-    AUTH_TOKEN_VSENG_XAMARIN_MAC_DEVICES_P12: ${{ parameters.xqaCertPass }}
-    AUTH_TOKEN_VSENG_XAMARIN_MAC_DEVICES_2_P12: ${{ parameters.xqaCertPass }}
-    SOURCES_DIR: $(Build.SourcesDirectory)
+      cd "$SOURCES_DIR/maccore/tools/"
+      ./install-qa-provisioning-profiles.sh -v
+    displayName: 'Add tests provisioning profiles'
+    timeoutInMinutes: 30
+    continueOnError: true # should not stop the build will result in test failures but we do want the pkg
+    env:
+      AUTH_TOKEN_GITHUB_COM: ${{ parameters.gitHubToken }}
+      AUTH_TOKEN_LA_DEV_APPLE_P12: ${{ parameters.xqaCertPass }}
+      AUTH_TOKEN_LA_DISTR_APPLE_P12: ${{ parameters.xqaCertPass }}
+      AUTH_TOKEN_LA_MAC_INSTALLER_DISTR_P12: ${{ parameters.xqaCertPass }}
+      AUTH_TOKEN_VSENG_XAMARIN_MAC_DEVICES_P12: ${{ parameters.xqaCertPass }}
+      AUTH_TOKEN_VSENG_XAMARIN_MAC_DEVICES_2_P12: ${{ parameters.xqaCertPass }}
+      SOURCES_DIR: $(Build.SourcesDirectory)
 
-- bash: |
-    set -x
-    set -e
+  - bash: |
+      set -x
+      set -e
 
-    echo "##vso[task.setvariable variable=macTestsPresent;isOutput=true]Succeeded"
-    RC=0
-    make -C $(Build.SourcesDirectory)/xamarin-macios/tests package-tests || RC=$?
-    if [ $RC -eq 0 ]; then
-      echo "Setting outpur var macTestsPresent to Succeeded"
       echo "##vso[task.setvariable variable=macTestsPresent;isOutput=true]Succeeded"
-    else
-      echo "Setting outpur var macTestsPresent to Failed"
-      echo "##vso[task.setvariable variable=macTestsPresent;isOutput=true]Failed"
-    fi
-    exit $RC
-    
-  name: macTestPkg
-  displayName: 'Package Xamarin.mac tests'
-  condition: and(succeeded(), contains(variables['configuration.RunMacTests'], 'True'))
-  continueOnError: true # not a terrible blocking issue
-  timeoutInMinutes: 60
+      RC=0
+      make -C $(Build.SourcesDirectory)/xamarin-macios/tests package-tests || RC=$?
+      if [ $RC -eq 0 ]; then
+        echo "Setting outpur var macTestsPresent to Succeeded"
+        echo "##vso[task.setvariable variable=macTestsPresent;isOutput=true]Succeeded"
+      else
+        echo "Setting outpur var macTestsPresent to Failed"
+        echo "##vso[task.setvariable variable=macTestsPresent;isOutput=true]Failed"
+      fi
+      exit $RC
+      
+    name: macTestPkg
+    displayName: 'Package Xamarin.mac tests'
+    condition: and(succeeded(), contains(variables['configuration.RunMacTests'], 'True'))
+    continueOnError: true # not a terrible blocking issue
+    timeoutInMinutes: 60
 
-- task: PublishPipelineArtifact@1
-  displayName: 'Publish Xamarin.Mac tests'
-  inputs:
-    targetPath: $(Build.SourcesDirectory)/xamarin-macios/tests/mac-test-package.7z
-    artifactName: mac-test-package
-  condition: and(succeeded(), contains(variables['configuration.RunMacTests'], 'True'))
-  continueOnError: true
+  - task: PublishPipelineArtifact@1
+    displayName: 'Publish Xamarin.Mac tests'
+    inputs:
+      targetPath: $(Build.SourcesDirectory)/xamarin-macios/tests/mac-test-package.7z
+      artifactName: mac-test-package
+    condition: and(succeeded(), contains(variables['configuration.RunMacTests'], 'True'))
+    continueOnError: true
 
-- bash: |
-    set -x
-    set -e
-    echo "Running tests on $AGENT_NAME"
-    echo "##vso[task.setvariable variable=TESTS_BOT;isOutput=true]$AGENT_NAME"
+- ${{ if eq(parameters.runTests, true) }}:
+  - bash: |
+      set -x
+      set -e
+      echo "Running tests on $AGENT_NAME"
+      echo "##vso[task.setvariable variable=TESTS_BOT;isOutput=true]$AGENT_NAME"
 
-    echo "##vso[task.setvariable variable=TESTS_RAN;isOutput=true]True"
-    rm -rf ~/.config/.mono/keypairs/
+      echo "##vso[task.setvariable variable=TESTS_RAN;isOutput=true]True"
+      rm -rf ~/.config/.mono/keypairs/
 
-    if [[ "$IsPR" == "True" ]]; then
-      TARGET='jenkins'
-    else
-      TARGET='wrench-jenkins'
-    fi
+      if [[ "$IsPR" == "True" ]]; then
+        TARGET='jenkins'
+      else
+        TARGET='wrench-jenkins'
+      fi
 
-    echo "Using target '$TARGET'"
+      echo "Using target '$TARGET'"
 
-    RC=0
-    make -C $(Build.SourcesDirectory)/xamarin-macios/tests "$TARGET" || RC=$?
+      RC=0
+      make -C $(Build.SourcesDirectory)/xamarin-macios/tests "$TARGET" || RC=$?
 
-    if [ $RC -eq 0 ]; then
-      echo "##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Succeeded"
-    else
+      if [ $RC -eq 0 ]; then
+        echo "##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Succeeded"
+      else
+        echo "##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Failed"
+      fi
+
+      if test -f "$(Build.SourcesDirectory)/xamarin-macios//jenkins/failure-stamp"; then
+        echo "Something went wrong:"
+        cat "$(Build.SourcesDirectory)/xamarin-macios//jenkins/pr-comments.md"
+        exit 1
+      fi
+    displayName: 'Run tests'
+    name: runTests # not to be confused with the displayName, this is used to later use the name of the step to access the output variables from an other job
+    timeoutInMinutes: 720
+    enabled: ${{ parameters.runTests }}
+    env:
+      IsPR: $(configuration.IsPR)
+      PR_ID: $(configuration.PR_ID)
+      GITHUB_TOKEN: $(GitHub.Token)  # used to filter the tests to be ran
+      BUILD_REVISION: jenkins
+      VSDROPS_URI: '${{ parameters.vsdropsPrefix }}/$(Build.BuildNumber)/$(Build.BuildId)/sim;/tests/' # uri used to create the vsdrops index using full uri
+
+
+  # Only executed when the tests failed, that means that we did have a timeout, and we could not set the status, this
+  # later results on an error when publishing the results, if we timeout, we ensure we set the needed vars
+  - bash: |
       echo "##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Failed"
-    fi
+    displayName: 'On tests timeout'
+    condition: failed()
 
-    if test -f "$(Build.SourcesDirectory)/xamarin-macios//jenkins/failure-stamp"; then
-      echo "Something went wrong:"
-      cat "$(Build.SourcesDirectory)/xamarin-macios//jenkins/pr-comments.md"
-      exit 1
-    fi
-  displayName: 'Run tests'
-  name: runTests # not to be confused with the displayName, this is used to later use the name of the step to access the output variables from an other job
-  timeoutInMinutes: 720
-  enabled: ${{ parameters.runTests }}
-  env:
-    IsPR: $(configuration.IsPR)
-    PR_ID: $(configuration.PR_ID)
-    GITHUB_TOKEN: $(GitHub.Token)  # used to filter the tests to be ran
-    BUILD_REVISION: jenkins
-    VSDROPS_URI: '${{ parameters.vsdropsPrefix }}/$(Build.BuildNumber)/$(Build.BuildId)/sim;/tests/' # uri used to create the vsdrops index using full uri
+  # Upload TestSummary as an artifact.
+  - task: PublishPipelineArtifact@1
+    displayName: 'Publish Artifact: TestSummary'
+    inputs:
+      targetPath: 'xamarin-macios/tests/TestSummary.md'
+      artifactName: TestSummary-sim
+    continueOnError: true
+    condition: always () # any task can write to TestSummary.md, so always try to upload it
 
+  - pwsh: |
+      $summaryName = "TestSummary.md"
+      $summaryPath = "$Env:SYSTEM_DEFAULTWORKINGDIRECTORY/xamarin-macios/tests/TestSummary.md"
+      if (Test-Path "$summaryPath" -PathType Leaf) {
+        Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=$summaryName;]$summaryPath"
+      }
+    displayName: Set TestSummary
+    condition: always () # any task can write to TestSummary.md, so always try to upload it
 
-# Only executed when the tests failed, that means that we did have a timeout, and we could not set the status, this
-# later results on an error when publishing the results, if we timeout, we ensure we set the needed vars
-- bash: |
-    echo "##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Failed"
-  displayName: 'On tests timeout'
-  condition: failed()
+  # Archive files for the Html Report so that the report can be easily uploaded as artifacts of the build.
+  - task: ArchiveFiles@1
+    displayName: 'Archive HtmlReport'
+    inputs:
+      rootFolder: 'xamarin-macios/jenkins-results'
+      includeRootFolder: false
+      archiveFile: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
+    continueOnError: true
+    condition: and(succeededOrFailed(), contains(variables['runTests.TESTS_RAN'], 'True')) # if tests did not run, there is nothing to do
 
-# Upload TestSummary as an artifact.
-- task: PublishPipelineArtifact@1
-  displayName: 'Publish Artifact: TestSummary'
-  inputs:
-    targetPath: 'xamarin-macios/tests/TestSummary.md'
-    artifactName: TestSummary-sim
-  continueOnError: true
-  condition: always () # any task can write to TestSummary.md, so always try to upload it
-
-- pwsh: |
-    $summaryName = "TestSummary.md"
-    $summaryPath = "$Env:SYSTEM_DEFAULTWORKINGDIRECTORY/xamarin-macios/tests/TestSummary.md"
-    if (Test-Path "$summaryPath" -PathType Leaf) {
-      Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=$summaryName;]$summaryPath"
-    }
-  displayName: Set TestSummary
-  condition: always () # any task can write to TestSummary.md, so always try to upload it
-
-# Archive files for the Html Report so that the report can be easily uploaded as artifacts of the build.
-- task: ArchiveFiles@1
-  displayName: 'Archive HtmlReport'
-  inputs:
-    rootFolder: 'xamarin-macios/jenkins-results'
-    includeRootFolder: false
-    archiveFile: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
-  continueOnError: true
-  condition: and(succeededOrFailed(), contains(variables['runTests.TESTS_RAN'], 'True')) # if tests did not run, there is nothing to do
-
-# Create HtmlReport artifact. This serves two purposes:
-# 1. It is the way we are going to share the HtmlReport with the publish_html job that is executed on a Windows machine.
-# 2. Users can download this if they want.
-- task: PublishPipelineArtifact@1
-  displayName: 'Publish Artifact: HtmlReport'
-  inputs:
-    targetPath: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
-    artifactName: HtmlReport-sim
-  continueOnError: true
-  condition: and(succeededOrFailed(), contains(variables['runTests.TESTS_RAN'], 'True')) # if tests did not run, there is nothing to do
+  # Create HtmlReport artifact. This serves two purposes:
+  # 1. It is the way we are going to share the HtmlReport with the publish_html job that is executed on a Windows machine.
+  # 2. Users can download this if they want.
+  - task: PublishPipelineArtifact@1
+    displayName: 'Publish Artifact: HtmlReport'
+    inputs:
+      targetPath: '$(Build.ArtifactStagingDirectory)/HtmlReport.zip'
+      artifactName: HtmlReport-sim
+    continueOnError: true
+    condition: and(succeededOrFailed(), contains(variables['runTests.TESTS_RAN'], 'True')) # if tests did not run, there is nothing to do
 
 # this will always be executed, is the default condition in the template
 - template: uninstall-certificates/v1.yml@templates
@@ -573,9 +581,8 @@ steps:
   displayName: 'Remove git creds store'
   condition: always()
 
-
-# Copy all the binlogs to a separate directory, keeping directory structure.
 - ${{ if eq(parameters.uploadBinlogs, true) }}:
+  # Copy all the binlogs to a separate directory, keeping directory structure.
   - script: |
       set -x
       mkdir -p $(Build.ArtifactStagingDirectory)/all-binlogs
