[CI] Sign .NET packages. (#10563)
* [CI] Sign .NET packages.

* [CI] Extract package signing from the 'Build Packages' step and do it after 'Build Nugets' so that Nugets can be signed too.

* Build packages for 'IndividualCI' as well.

This happens when pushing additional commits to a PR.

diff --git a/tools/devops/automation/templates/build/build.yml b/tools/devops/automation/templates/build/build.yml
--- a/tools/devops/automation/templates/build/build.yml
+++ b/tools/devops/automation/templates/build/build.yml
@@ -156,7 +156,7 @@ steps:
     # decide if we are dealing with a PR or a re-triggered PR or a build from
     # a branch in origin
     
-    if ($buildReason -eq "PullRequest" -or (($buildReason -eq "Manual") -and ($buildSourceBranchName -eq "merge")) ) {
+    if ($buildReason -eq "PullRequest" -or (($buildReason -eq "Manual" -or $buildReason -eq "IndividualCI") -and ($buildSourceBranchName -eq "merge")) ) {
       $configVars.Add("IsPR", "True")
 
       if ($Env:BuildPackage -eq "True") {
@@ -284,6 +284,22 @@ steps:
     rm -Rf $(Build.SourcesDirectory)/package/*.pkg
     rm -Rf $(Build.SourcesDirectory)/package/notarized/*.pkg
     time make -C $(Build.SourcesDirectory)/xamarin-macios/ package
+  name: packages
+  displayName: 'Build Packages'
+  condition: and(succeeded(), contains(variables['configuration.BuildPkgs'], 'True'))
+  timeoutInMinutes: 180
+
+# build nugets
+- bash:  $(Build.SourcesDirectory)/xamarin-macios/tools/devops/automation/scripts/bash/build-nugets.sh
+  displayName: 'Build Nugets'
+  condition: and(succeeded(), contains(variables['configuration.BuildNugets'], 'True'))
+  continueOnError: true # should not stop the build since is not official just yet.
+  timeoutInMinutes: 180
+
+# build not signed .pkgs for the SDK
+- bash: |
+    set -x
+    set -e
 
     # output vars for other steps to use and not need to recomputed the paths
     IOS_PKG=$(find $(Build.SourcesDirectory)/package -type f -name "xamarin.ios-*" | xargs basename)
@@ -303,16 +319,44 @@ steps:
       echo "##vso[task.setvariable variable=MAC_PKG;]$MAC_PKG"
       echo "Xamarin.Mac package found at $MAC_PKG"
     fi
-  name: packages
-  displayName: 'Build Packages'
-  condition: and(succeeded(), contains(variables['configuration.BuildPkgs'], 'True'))
-  timeoutInMinutes: 180
 
-# build nugets
-- bash:  $(Build.SourcesDirectory)/xamarin-macios/tools/devops/automation/scripts/bash/build-nugets.sh
-  displayName: 'Build Nugets'
-  condition: and(succeeded(), contains(variables['configuration.BuildNugets'], 'True'))
-  continueOnError: true # should not stop the build since is not official just yet.
+    IOS_DOTNET_PKG=$(find $(Build.SourcesDirectory)/package -type f -name "Microsoft.iOS.Bundle*.pkg" | xargs basename)
+    if [ -z "$IOS_DOTNET_PKG" ]; then
+      echo "Microsoft.iOS bundle not found."
+    else
+      IOS_DOTNET_PKG="$(Build.SourcesDirectory)/package/$IOS_DOTNET_PKG"
+      echo "##vso[task.setvariable variable=IOS_DOTNET_PKG;]$IOS_DOTNET_PKG"
+      echo "Microsoft.iOS bundle found at $IOS_DOTNET_PKG"
+    fi
+
+    TVOS_DOTNET_PKG=$(find $(Build.SourcesDirectory)/package -type f -name "Microsoft.tvOS.Bundle*.pkg" | xargs basename)
+    if [ -z "$TVOS_DOTNET_PKG" ]; then
+      echo "Microsoft.tvOS bundle not found."
+    else
+      TVOS_DOTNET_PKG="$(Build.SourcesDirectory)/package/$TVOS_DOTNET_PKG"
+      echo "##vso[task.setvariable variable=TVOS_DOTNET_PKG;]$TVOS_DOTNET_PKG"
+      echo "Microsoft.tvOS package found at $TVOS_DOTNET_PKG"
+    fi
+
+    WATCHOS_DOTNET_PKG=$(find $(Build.SourcesDirectory)/package -type f -name "Microsoft.watchOS.Bundle*.pkg" | xargs basename)
+    if [ -z "$WATCHOS_DOTNET_PKG" ]; then
+      echo "Microsoft.watchOS bundle not found."
+    else
+      WATCHOS_DOTNET_PKG="$(Build.SourcesDirectory)/package/$WATCHOS_DOTNET_PKG"
+      echo "##vso[task.setvariable variable=WATCHOS_DOTNET_PKG;]$WATCHOS_DOTNET_PKG"
+      echo "Microsoft.watchOS package found at $WATCHOS_DOTNET_PKG"
+    fi
+
+    MACOS_DOTNET_PKG=$(find $(Build.SourcesDirectory)/package -type f -name "Microsoft.macOS.Bundle*.pkg" | xargs basename)
+    if [ -z "$MACOS_DOTNET_PKG" ]; then
+      echo "Microsoft.macOS bundle not found."
+    else
+      MACOS_DOTNET_PKG="$(Build.SourcesDirectory)/package/$MACOS_DOTNET_PKG"
+      echo "##vso[task.setvariable variable=MACOS_DOTNET_PKG;]$MACOS_DOTNET_PKG"
+      echo "Microsoft.macOS package found at $MACOS_DOTNET_PKG"
+    fi
+  displayName: 'Sign Packages'
+  condition: and(succeeded(), contains(variables['configuration.BuildPkgs'], 'True'))
   timeoutInMinutes: 180
 
 - task: NuGetCommand@2
@@ -337,7 +381,7 @@ steps:
 
 - bash: |
     security unlock-keychain -p $PRODUCTSIGN_KEYCHAIN_PASSWORD builder.keychain
-    PACKAGES="$IOS_PKG $MAC_PKG"
+    PACKAGES="$IOS_PKG $MAC_PKG $IOS_DOTNET_PKG $TVOS_DOTNET_PKG $WATCHOS_DOTNET_PKG $MACOS_DOTNET_PKG"
     echo "Packages found at $PACKAGES"
 
     echo "$PACKAGES" | xargs python $(Build.SourcesDirectory)/release-scripts/sign_and_notarize.py --no_notarization -a "$APP_ID" -i "$INSTALL_ID" -u "$APPLE_ACCOUNT" -p "$APPLE_PASS" -t "$TEAM_ID" -d $(Build.SourcesDirectory)/package/notarized -e "$MAC_ENTITLEMENTS" -k "$KEYCHAIN"
