[devops] Improve failure reporting for tests on older macOS bots.

diff --git a/tools/devops/automation/templates/mac/build.yml b/tools/devops/automation/templates/mac/build.yml
--- a/tools/devops/automation/templates/mac/build.yml
+++ b/tools/devops/automation/templates/mac/build.yml
@@ -12,12 +12,22 @@ parameters:
 - name: keyringPass
   type: string
 
+variables:
+  GITHUB_FAILURE_COMMENT_FILE: $(System.DefaultWorkingDirectory)/github-comment-file.md
+
 steps:
 
 - checkout: self
   path: s/xamarin-macios
 - checkout: maccore
   persistCredentials: true  # hugely important, else there are some scripts that check a single file from maccore that will fail
+
+# Write a generic failure message to the failure comment file, so a failure will be reported
+# if something goes wrong before we successfully complete the tests (in which case we delete the file).
+- bash: |
+    echo "Tests on macOS $CONTEXT failed for unknown reasons." > "$GITHUB_FAILURE_COMMENT_FILE"
+    Set-GitHubStatus -Status "pending" -Description "Tests on macOS $Env:CONTEXT have started." -Context "$Env:CONTEXT"
+  displayName: "Initialize state"
 
 - bash: |
     RC=0
@@ -59,7 +69,6 @@ steps:
       echo "##vso[task.setvariable variable=VM_VENDOR]VirtualBox"
     fi
 
-    
     if [[ $(ioreg -l | grep -e 'Parallels' | wc -l) -ne 0 ]]; then
       echo "Using Parallels virtualization."
       echo "##vso[task.setvariable variable=VM_VENDOR]Parallels"
@@ -85,11 +94,8 @@ steps:
     Import-Module ./VSTS.psm1
     Import-Module ./GitHub.psm1
     if ( -not (Test-HDFreeSpace -Size 5)) {
-      Set-GitHubStatus -Status "error" -Description "Not enough free space in the host." -Context "$Env:CONTEXT"
-      New-GitHubComment -Header "Tests failed catastrophically on $Env:CONTEXT" -Emoji ":fire:" -Description "Not enough free space in the host."
-      Stop-Pipeline
-    } else {
-      Set-GitHubStatus -Status "pending" -Description "Tests $Env:CONTEXT on VSTS have been started." -Context "$Env:CONTEXT"
+      Set-Content -Path "$GITHUB_FAILURE_COMMENT_FILE" -Value "Not enough free space in the host."
+      exit 1
     }
   env:
     BUILD_REVISION: $(Build.SourceVersion)
@@ -98,7 +104,6 @@ steps:
     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
   displayName: 'Check HD Free Space'
   timeoutInMinutes: 5
-  condition: succeededOrFailed() # we do not care about the previous step
 
 - task: xamops.azdevex.provisionator-task.provisionator@2
   displayName: 'Provision Brew components'
@@ -148,22 +153,7 @@ steps:
   displayName: 'Nuke Provisionator Tool Cache'
   condition: ${{ parameters.clearProvisionatorCache }}
 
-# sometimes the make that creates the pkgs fails.
-- pwsh: |
-    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\automation\scripts\GitHub.psm1 
-
-    if ($Env:MAC_TESTS_PRESENT -eq "Failed") {
-      Set-GitHubStatus -Status "error" -Description "Mac tests were not packaged." -Context "$Env:CONTEXT"
-      New-GitHubComment -Header "Tests failed catastrophically on $Env:CONTEXT" -Emoji ":fire:" -Description "Mac tests were not packaged."
-      Stop-Pipeline
-    } 
-  displayName: Validate tests package
-  env:
-    CONTEXT: ${{ parameters.statusContext }}
-    BUILD_REVISION: $(Build.SourceVersion)
-    GITHUB_TOKEN: $(GitHub.Token)
-    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-
+# Go get the tests!
 - task: DownloadPipelineArtifact@2
   displayName: Download Mac tests
   inputs:
@@ -171,11 +161,18 @@ steps:
     allowFailedBuilds: true
     path: $(Build.SourcesDirectory)/artifacts/tmp
 
+# sometimes the make that creates the pkgs fails.
 - bash: |
+    if ! test -f $(Build.SourcesDirectory)/artifacts/tmp/mac-test-package/mac-test-package.7z; then
+      echo "No test package could be found for tests on macOS $CONTEXT" > "$GITHUB_FAILURE_COMMENT_FILE"
+      exit 1
+    fi
     ls -Rla $(Build.SourcesDirectory)/artifacts/tmp
     7z x $(Build.SourcesDirectory)/artifacts/tmp/mac-test-package/mac-test-package.7z -o$(Build.SourcesDirectory)/artifacts/ -bb1
     ls -Rla $(Build.SourcesDirectory)/artifacts/mac-test-package
   displayName: Expand tests.
+  env:
+    CONTEXT: ${{ parameters.statusContext }}
 
 - bash: |
     ls -Rla $(Build.SourcesDirectory)/artifacts
@@ -197,6 +194,9 @@ steps:
 
     [System.Collections.Generic.List[string]]$failures = @()
 
+    # Claim that the tests timed out before we start
+    Set-Content -Path "$Env:GITHUB_FAILURE_COMMENT_FILE" -Value "Tests timed out"
+
     $macTest = @("dontlink", "introspection", "linksdk", "linkall", "xammac_tests", "monotouch-test")
     foreach ($t in $macTest) {
       $testName = "exec-$t"
@@ -212,7 +212,7 @@ steps:
     if ($failures.Count -ne 0) {
       # post status and comment in the build
       $failedTestsStr = [string]::Join(",",$failures)
-      Set-GitHubStatus -Status "error" -Description "Xamarin.Mac tests on macOS $Env:CONTEXT failed ($failedTestsStr)." -Context "$Env:CONTEXT"
+      Set-GitHubStatus -Status "error" -Description "Tests on macOS $Env:CONTEXT failed ($failedTestsStr)." -Context "$Env:CONTEXT"
       # build message
       $msg = [System.Text.StringBuilder]::new()
       $msg.AppendLine("Failed tests are:")
@@ -221,12 +221,14 @@ steps:
       {
           $msg.AppendLine("* $test")
       }
-      $request = New-GitHubComment -Header "Tests failed on macOS $Env:CONTEXT" -Description "Tests failed on $Env:CONTEXT." -Message $msg.ToString() -Emoji ":x:"
+
+      # We failed, so write to the comment file why we failed.
+      Set-Content -File "$Env:GITHUB_FAILURE_COMMENT_FILE" -Value "$msg"
     } else {
-      Set-GitHubStatus -Status "success" -Description "Tests passed on macOS $Env:CONTEXT passed." -Context "$Env:CONTEXT"
-      $request = New-GitHubComment -Header "Tests passed on macOS $Env:CONTEXT" -Description "Tests passed" -Message "**All** tests on macOS $Env:CONTEXT passed." -Emoji ":white_check_mark:"
+      # We succeeded, so remove the failure comment file.
+      Remove-Item -Path "$Env:GITHUB_FAILURE_COMMENT_FILE"
     }
-    touch $testsPath/test-run-completed
+
     # we set the result to 0, the reason is that release pipelines do not like failing tests,
     # yet we do have some  flacky ones, this will allow the release to run. The comment will let use know that we failed
     exit 0  
@@ -240,16 +242,19 @@ steps:
     MONO_DEBUG: no-gdb-backtrace
   continueOnError: true
 
+# Make sure to report any errors
 - pwsh: |
     Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\automation\scripts\GitHub.psm1
-    $testsPath = "$(Build.SourcesDirectory)/artifacts/mac-test-package/tests"
-    if (-not ([IO.File]::Exists("$testsPath/test-run-completed"))) {
-      Set-GitHubStatus -Status "error" -Description "Tests timed out on macOS $Env:CONTEXT." -Context "$Env:CONTEXT"
-      $request = New-GitHubComment -Header "Tests timed out on macOS $Env:CONTEXT" -Description "" -Message "" -Emoji ":x:"
+    if (Test-Path -Path "$Env:GITHUB_FAILURE_COMMENT_FILE" -Leaf)  {
+      Set-GitHubStatus -Status "error" -Description "Tests on macOS $Env:CONTEXT failed." -Context "$Env:CONTEXT"
+      New-GitHubCommentFromFile -Header "Tests on macOS $Env:CONTEXT failed" -Emoji ":x:" -Path "$Env:GITHUB_FAILURE_COMMENT_FILE"
+    } else {
+      Set-GitHubStatus -Status "success" -Description "Tests on macOS $Env:CONTEXT passed." -Context "$Env:CONTEXT"
+      New-GitHubComment -Header "Tests on macOS $Env:CONTEXT passed" -Description "Tests passed" -Message "**All** tests on macOS $Env:CONTEXT passed." -Emoji ":white_check_mark:"
     }
-  displayName: 'Report test timeout'
+  displayName: 'Report results to GitHub'
   timeoutInMinutes: 5
-  condition: succeededOrFailed() # in particular we care if something failed
+  condition: always() # in particular we care if something failed, but let's always run just in case
   continueOnError: true
   env:
     CONTEXT: ${{ parameters.statusContext }}
