Show better error when the mono archive isn't available. Fixes xamarin-macios/maccore#1655. (#6155)
* Show better error when the mono archive isn't available. Fixes xamarin-macios/maccore#1655.

Fixes https://github.com/xamarin/maccore/issues/1655.

* [jenkins] Show better build failure in the build report PR comment.

diff --git a/builds/Makefile b/builds/Makefile
--- a/builds/Makefile
+++ b/builds/Makefile
@@ -8,6 +8,8 @@ download: downloads/$(basename $(MONO_IOS_FILENAME)) downloads/$(basename $(MONO
 downloads/$(basename $(MONO_IOS_FILENAME)): MONO_URL=$(MONO_IOS_URL)
 downloads/$(basename $(MONO_MAC_FILENAME)): MONO_URL=$(MONO_MAC_URL)
 
+include $(TOP)/mk/colors.mk
+
 # This target downloads the mono archives, there's one for Xamarin.iOS and one for Xamarin.Mac.
 # If doing many clean builds, it's possible to copy the downloaded zip file to ~/Library/Caches/xamarin-macios
 # to avoid having to download it every time. The zip files have to be copied manually, otherwise
@@ -19,7 +21,14 @@ downloads/$(MONO_IOS_FILENAME) downloads/$(MONO_MAC_FILENAME):
 		echo "Found a cached version of $(MONO_URL) in ~/Library/Caches/xamarin-macios/$(notdir $@)."; \
 		$(CP) ~/Library/Caches/xamarin-macios/$(notdir $@) $@.tmp; \
 	else \
-		curl -f -L $(if $(V),-v,-s) $(MONO_URL) --output $@.tmp; \
+		EC=0; \
+		curl -f -L $(if $(V),-v,-s) $(MONO_URL) --output $@.tmp || EC=$$?; \
+		if [[ x$$EC == x22 ]]; then \
+			MSG="Could not download the archive %s because the URL doesn't exist. This can happen if bumping mono very soon after the corresponding commit was pushed to mono (i.e. the archive hasn't been built yet). If so, please wait a bit and try again."; \
+			printf "$(COLOR_RED)*** $$MSG$(COLOR_CLEAR)\n" "$(notdir $@)"; \
+			if test -n "$$FAILURE_REASON_PATH"; then printf "$$MSG\n" "[$(notdir $@)]($(MONO_URL))" >> "$$FAILURE_REASON_PATH"; fi; \
+		fi; \
+		if [[ x$$EC != x0 ]]; then exit $$EC; fi; \
 	fi
 	$(Q) mv $@.tmp $@
 	$(Q) echo "Downloaded $(MONO_URL)"
