[DevOps] Allow to use vsdrops AND xamarin storage. (#8916)
Use both in those labs that support xamarin-storage so that we have a
backup. To do so, move the parameter to be a bool but keep the rest of
the logic the same.


Co-authored-by: Rolf Bjarne Kvinge <rolf@xamarin.com>

diff --git a/tools/devops/device-tests/templates/device-tests.yml b/tools/devops/device-tests/templates/device-tests.yml
--- a/tools/devops/device-tests/templates/device-tests.yml
+++ b/tools/devops/device-tests/templates/device-tests.yml
@@ -22,9 +22,12 @@ parameters:
   type: boolean
   default: false
 
-- name: htmlReportStorage
+- name: useXamarinStorage
+  type: boolean 
+  default: false  # xamarin-storage will disappear, so by default do not use it
+
+- name: vsdropsPrefix
   type: string
-  default: xamarin-storage # takes two different values, 'xamarin-storage' or 'vsdrops'
 
 steps:
 
@@ -235,34 +238,46 @@ steps:
 
     echo "Html Report: http://xamarin-storage/$P/jenkins-results/tests/index.html"
   displayName: 'Print Html Report link'
-  condition: and(always(), eq('${{ parameters.htmlReportStorage }}', 'xamarin-storage')) # execute always but when we are using vsdrops since we want to send the message and the url at the same time
+  condition: and(always(), ${{ parameters.useXamarinStorage }})
 
 # Run tests. If we are using xamarin-storage add a periodic command to be executed by xharness, else, since we are using vsdrops do nothing.
 - bash: |
     set -x
     set -e
+    echo 'Use xamarin storage $USE_XAMARIN_STORAGE'
 
     cd $WORKING_DIR/xamarin-macios
-    if [[ "$HTML_STORAGE" == "xamarin-storage" ]]; then
+    if [[ "$USE_XAMARIN_STORAGE" == "True" ]]; then
       EC=0
       ssh builder@xamarin-storage "mkdir -p /volume1/storage/$XAMARIN_STORAGE_PATH" || EC=$?
       if [ $EC -eq 0 ]; then
+        echo '##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]false'
+        echo '##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]$XAMARIN_STORAGE_PATH'
         export TESTS_PERIODIC_COMMAND="--periodic-interval 10 --periodic-command rsync --periodic-command-arguments '-avz -e \"ssh\" $PWD/jenkins-results builder@xamarin-storage:/volume1/storage/$XAMARIN_STORAGE_PATH'"
       else
-        echo "##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED]true"
+        echo '##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]true'
+        echo '##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]""'
       fi
     fi
 
     make -C builds download -j || true
     make -C builds downloads -j || true
     make -C builds .stamp-mono-ios-sdk-destdir -j || true
-    MONO_ENV_OPTIONS=--trace=E:all make -C tests vsts-device-tests
+    EC=0
+    MONO_ENV_OPTIONS=--trace=E:all make -C tests vsts-device-tests || EC=$?
+    if [ $EC -eq 0 ]; then
+      echo '##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Succeeded'
+    else
+      echo '##vso[task.setvariable variable=TESTS_JOBSTATUS;isOutput=true]Failed'
+    fi
   env:
     WORKING_DIR: $(System.DefaultWorkingDirectory) 
     XAMARIN_STORAGE_PATH: $(XAMARIN_STORAGE_PATH)
     TESTS_EXTRA_ARGUMENTS: ${{ parameters.testsLabels }}
-    HTML_STORAGE: ${{ parameters.htmlReportStorage }}
+    USE_XAMARIN_STORAGE: '${{ parameters.useXamarinStorage }}'
+    VSDROPS_URI: '${{ parameters.vsdropsPrefix }}/$(Build.BuildNumber)/$(Build.BuildId);/tests/' # uri used to create the vsdrops index using full uri
   displayName: 'Run tests'
+  name: runTests # not to be confused with the displayName, this is used to later use the name of the step to access the output variables from an other job
   timeoutInMinutes: 600
 
 # Upload TestSummary as an artifact.
@@ -270,25 +285,9 @@ steps:
   displayName: 'Publish Artifact: TestSummary'
   inputs:
     targetPath: 'xamarin-macios/tests/TestSummary.md'
-    artifactName: TestSummary.md
+    artifactName: TestSummary
   continueOnError: true
   condition: succeededOrFailed()
-
-# Use the cmdlet to post a new summary comment. The cmdlet checks if we have the TestSummary.md file or not. It will also add the appropiate links to the commnet. 
-# This step is ONLY executed when we selected the xamarin-storage option. If we use vsdrops we want to wait until the publish_html job to do it so that we can 
-# calculate the url of the html report based in the vsdrop path.
-- pwsh: |
-    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY/xamarin-macios/tools/devops/device-tests/scripts/GitHub.psm1 
-    New-GitHubSummaryComment -Context "$Env:CONTEXT" -XamarinStoragePath "$Env:XAMARIN_STORAGE_PATH" -TestSummaryPath "$Env:SYSTEM_DEFAULTWORKINGDIRECTORY/xamarin-macios/tests/TestSummary.md"
-  env:
-    BUILD_REVISION: $(BUILD_REVISION)
-    CONTEXT: ${{ parameters.statusContext }}
-    GITHUB_TOKEN: $(GitHub.Token)
-    XAMARIN_STORAGE_PATH: $(XAMARIN_STORAGE_PATH) # could be null if the step was not executed if we use vsdrops, the cmdlet will know how to handle that case
-    XAMARIN_STORAGE_REACHED: $(XAMARIN_STORAGE_FAILED) # could not reach xamarin-storage, either the bot is not in the vpn or it finally failed
-  displayName: 'Add summaries'
-  condition: and(always(), eq('${{ parameters.htmlReportStorage }}', 'xamarin-storage')) # execute always but when we are using vsdrops since we want to send the message and the url at the same time from the pusblish_hml job
-  timeoutInMinutes: 1
 
 # Upload test results to vsts.
 - task: PublishTestResults@2
