[DevOps] Fix issues with the xm stroage path.
For some reason, and it is very probably a bug in the azurepipelines,
the following bash code creates a path with an extra single quote at the
end:

```bash
 P=jenkins/xamarin-macios/$BUILD_LANE/$BUILD_REVISION/$ID/device-tests

echo "##vso[task.setvariable variable=XM_STORAGE_PATH]$P"
```

* Should it do it? Not, it should not.
* Does it do it? Yes, it does.

We work around it via td -d \'\" and remove all single and double quotes
in the string. How long did it take to discover this? More than it
should have.

There is another interesting bug with the variable expansion, the
following
```bash
echo '##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]$P'
```
Does not equal
```bash
echo '##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]'$P
```

The first will not expand the variable, the second one will. We do need
the value of $P not '$P'.

diff --git a/tools/devops/device-tests/templates/device-tests.yml b/tools/devops/device-tests/templates/device-tests.yml
--- a/tools/devops/device-tests/templates/device-tests.yml
+++ b/tools/devops/device-tests/templates/device-tests.yml
@@ -230,7 +230,7 @@ steps:
 
     P=jenkins/xamarin-macios/$BUILD_LANE/$BUILD_REVISION/$ID/device-tests
 
-    echo "##vso[task.setvariable variable=XAMARIN_STORAGE_PATH]$P"
+    echo "##vso[task.setvariable variable=XM_STORAGE_PATH]$P"
 
     X="#vso"
     set +x
@@ -246,24 +246,24 @@ steps:
 - bash: |
     set -x
     set -e
-    echo 'Use xamarin storage $USE_XAMARIN_STORAGE'
+    P=$(echo $XM_STORAGE_PATH | tr -d \'\")
 
     cd $WORKING_DIR/xamarin-macios
     if [[ "$USE_XAMARIN_STORAGE" == "True" ]]; then
       if nc -z xamarin-storage 22 2>/dev/null; then
-        EC=0
-        MKSTORAGE='ssh builder@xamarin-storage "mkdir -p /volume1/storage/$XAMARIN_STORAGE_PATH"'
-        eval $MKSTORAGE || EC=$?
-        if [ $EC -eq 0 ]; then
-          echo '##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]$XAMARIN_STORAGE_PATH'
-          echo '##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]false'
-          export TESTS_PERIODIC_COMMAND="--periodic-interval 10 --periodic-command rsync --periodic-command-arguments '-avz -e \"ssh\" $PWD/jenkins-results builder@xamarin-storage:/volume1/storage/$XAMARIN_STORAGE_PATH'"
+        ssh builder@xamarin-storage "mkdir -p /volume1/storage/$P"
+        if [[ $? = 1 ]]; then
+          echo "Remote mkdir failed"
+          echo "##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]true"
+          echo "##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]"
         else
-          echo '##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]true'
+          echo "##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]$P"
+          echo "##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]false"
+          export TESTS_PERIODIC_COMMAND="--periodic-interval 10 --periodic-command rsync --periodic-command-arguments '-avz -e \"ssh\" $PWD/jenkins-results builder@xamarin-storage:/volume1/storage/$P'"
         fi
       else
-        echo '##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]true'
-        echo '##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]""'
+        echo "##vso[task.setvariable variable=XAMARIN_STORAGE_FAILED;isOutput=true]true"
+        echo "##vso[task.setvariable variable=XAMARIN_STORAGE_PATH;isOutput=true]"
       fi
     fi
 
@@ -279,7 +279,6 @@ steps:
     fi
   env:
     WORKING_DIR: $(System.DefaultWorkingDirectory) 
-    XAMARIN_STORAGE_PATH: $(XAMARIN_STORAGE_PATH)
     TESTS_EXTRA_ARGUMENTS: ${{ parameters.testsLabels }}
     USE_XAMARIN_STORAGE: '${{ parameters.useXamarinStorage }}'
     VSDROPS_URI: '${{ parameters.vsdropsPrefix }}/$(Build.BuildNumber)/$(Build.BuildId);/tests/' # uri used to create the vsdrops index using full uri
